<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateSystemSettingsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('system_settings', function (Blueprint $table) {
            $table->id();
            $table->string('version', 50)->nullable();
            $table->string('install_date', 50)->nullable();
            $table->enum('use_non_latin', ['0', '1'])->default('0');
            $table->enum('webroot_writable', ['0', '1'])->default('1');
            $table->enum('enable_queuemetrics_logging', ['0', '1'])->default('0');
            $table->string('queuemetrics_server_ip', 15)->nullable();
            $table->string('queuemetrics_dbname', 50)->nullable();
            $table->string('queuemetrics_login', 50)->nullable();
            $table->string('queuemetrics_pass', 50)->nullable();
            $table->string('queuemetrics_url', 255)->nullable();
            $table->string('queuemetrics_log_id', 10)->default('VIC');
            $table->string('queuemetrics_eq_prepend', 255)->default('NONE');
            $table->enum('vicidial_agent_disable', ['NOT_ACTIVE', 'LIVE_AGENT', 'EXTERNAL', 'ALL'])->default('ALL');
            $table->enum('allow_sipsak_messages', ['0', '1'])->default('0');
            $table->string('admin_home_url', 255)->default('../vicidial/welcome.php');
            $table->enum('enable_agc_xfer_log', ['0', '1'])->default('0');
            $table->unsignedInteger('db_schema_version')->default(0);
            $table->unsignedInteger('auto_user_add_value')->default(101);
            $table->string('timeclock_end_of_day', 4)->default('0000');
            $table->date('timeclock_last_reset_date')->nullable();
            $table->string('vdc_header_date_format', 50)->default('MS_DASH_24HR 2008-06-24 23:59:59');
            $table->string('vdc_customer_date_format', 50)->default('AL_TEXT_AMPM OCT 24, 2008 11:59:59 PM');
            $table->string('vdc_header_phone_format', 50)->default('US_PARN (000)000-0000');
            $table->enum('vdc_agent_api_active', ['0', '1'])->default('0');
            $table->dateTime('qc_last_pull_time')->nullable();
            $table->enum('enable_vtiger_integration', ['0', '1'])->default('0');
            $table->string('vtiger_server_ip', 15)->nullable();
            $table->string('vtiger_dbname', 50)->nullable();
            $table->string('vtiger_login', 50)->nullable();
            $table->string('vtiger_pass', 50)->nullable();
            $table->string('vtiger_url', 255)->nullable();
            $table->enum('qc_features_active', ['1', '0'])->default('0');
            $table->enum('outbound_autodial_active', ['1', '0'])->default('1');
            $table->unsignedSmallInteger('outbound_calls_per_second')->default(10);
            $table->enum('enable_tts_integration', ['0', '1'])->default('0');
            $table->enum('agentonly_callback_campaign_lock', ['0', '1'])->default('1');
            $table->enum('sounds_central_control_active', ['0', '1'])->default('0');
            $table->string('sounds_web_server', 50)->default('127.0.0.1');
            $table->string('sounds_web_directory', 255)->nullable();
            $table->string('active_voicemail_server', 15)->nullable();
            $table->string('auto_dial_limit', 5)->default('20');
            $table->enum('user_territories_active', ['0', '1'])->default('0');
            $table->enum('allow_custom_dialplan', ['0', '1'])->default('1');
            $table->dateTime('db_schema_update_date')->nullable();
            $table->enum('enable_second_webform', ['0', '1'])->default('1');
            $table->enum('default_webphone', ['1', '0'])->default('0');
            $table->enum('default_external_server_ip', ['1', '0'])->default('0');
            $table->string('webphone_url', 255)->nullable();
            $table->string('static_agent_url', 255)->nullable();
            $table->string('default_phone_code', 8)->nullable();
            $table->enum('enable_agc_dispo_log', ['0', '1'])->nullable()->default('0');
            $table->text('custom_dialplan_entry')->nullable();
            $table->enum('queuemetrics_loginout', ['STANDARD', 'CALLBACK', 'NONE'])->default('STANDARD');
            $table->enum('callcard_enabled', ['1', '0'])->default('0');
            $table->enum('queuemetrics_callstatus', ['0', '1'])->default('1');
            $table->string('default_codecs', 100)->nullable();
            $table->enum('custom_fields_enabled', ['0', '1'])->default('0');
            $table->string('admin_web_directory', 255)->default('vicidial');
            $table->string('label_title', 60)->nullable();
            $table->string('label_first_name', 60)->nullable();
            $table->string('label_middle_initial', 60)->nullable();
            $table->string('label_last_name', 60)->nullable();
            $table->string('label_address1', 60)->nullable();
            $table->string('label_address2', 60)->nullable();
            $table->string('label_address3', 60)->nullable();
            $table->string('label_city', 60)->nullable();
            $table->string('label_state', 60)->nullable();
            $table->string('label_province', 60)->nullable();
            $table->string('label_postal_code', 60)->nullable();
            $table->string('label_vendor_lead_code', 60)->nullable();
            $table->string('label_gender', 60)->nullable();
            $table->string('label_phone_number', 60)->nullable();
            $table->string('label_phone_code', 60)->nullable();
            $table->string('label_alt_phone', 60)->nullable();
            $table->string('label_security_phrase', 60)->nullable();
            $table->string('label_email', 60)->nullable();
            $table->string('label_comments', 60)->nullable();
            $table->string('slave_db_server', 50)->nullable();
            $table->string('reports_use_slave_db', 2000)->nullable();
            $table->string('webphone_systemkey', 100)->nullable();
            $table->enum('first_login_trigger', ['Y', 'N'])->default('N');
            $table->string('hosted_settings', 100)->nullable();
            $table->string('default_phone_registration_password', 20)->default('test');
            $table->string('default_phone_login_password', 20)->default('test');
            $table->string('default_server_password', 20)->default('test');
            $table->tinyInteger('admin_modify_refresh')->unsigned()->default(0);
            $table->enum('nocache_admin', ['0', '1'])->default('1');
            $table->enum('generate_cross_server_exten', ['0', '1'])->default('0');
            $table->enum('queuemetrics_addmember_enabled', ['0', '1'])->default('0');
            $table->string('queuemetrics_dispo_pause', 6)->nullable();
            $table->string('label_hide_field_logs', 6)->default('Y');
            $table->enum('queuemetrics_pe_phone_append', ['0', '1'])->default('0');
            $table->enum('test_campaign_calls', ['0', '1'])->default('0');
            $table->enum('agents_calls_reset', ['0', '1'])->default('1');
            $table->text('voicemail_timezones')->nullable();
            $table->string('default_voicemail_timezone', 30)->default('eastern');
            $table->string('default_local_gmt', 6)->default('-5.00');
            $table->enum('noanswer_log', ['Y', 'N'])->default('N');
            $table->string('alt_log_server_ip', 50)->nullable();
            $table->string('alt_log_dbname', 50)->nullable();
            $table->string('alt_log_login', 50)->nullable();
            $table->string('alt_log_pass', 50)->nullable();
            $table->string('tables_use_alt_log_db', 2000)->nullable();
            $table->enum('did_agent_log', ['Y', 'N'])->default('N');
            $table->enum('campaign_cid_areacodes_enabled', ['0', '1'])->default('1');
            $table->tinyInteger('pllb_grouping_limit')->default(100);
            $table->enum('did_ra_extensions_enabled', ['0', '1'])->default('0');
            $table->enum('expanded_list_stats', ['0', '1'])->default('1');
            $table->enum('contacts_enabled', ['0', '1'])->default('0');
            $table->string('svn_version', 100)->nullable();
            $table->enum('call_menu_qualify_enabled', ['0', '1'])->default('0');
            $table->enum('admin_list_counts', ['0', '1'])->default('1');
            $table->enum('allow_voicemail_greeting', ['0', '1'])->default('0');
            $table->text('audio_store_purge')->nullable();
            $table->integer('svn_revision')->default(0);
            $table->string('queuemetrics_socket', 20)->default('NONE');
            $table->text('queuemetrics_socket_url')->nullable();
            $table->enum('enhanced_disconnect_logging', ['0', '1', '2', '3', '4', '5', '6'])->default('0');
            $table->enum('allow_emails', ['0', '1'])->default('0');
            $table->enum('level_8_disable_add', ['0', '1'])->default('0');
            $table->enum('pass_hash_enabled', ['0', '1'])->default('0');
            $table->string('pass_key', 100)->nullable();
            $table->tinyInteger('pass_cost')->unsigned()->default(2);
            $table->enum('disable_auto_dial', ['0', '1'])->default('0');
            $table->enum('queuemetrics_record_hold', ['0', '1'])->default('0');
            $table->enum('country_code_list_stats', ['0', '1'])->default('0');
            $table->datetime('reload_timestamp')->nullable();
            $table->enum('queuemetrics_pause_type', ['0', '1'])->default('0');
            $table->enum('frozen_server_call_clear', ['0', '1'])->default('0');
            $table->enum('callback_time_24hour', ['0', '1'])->default('0');
            $table->text('active_modules')->nullable();
            $table->enum('allow_chats', ['0', '1'])->default('0');
            $table->enum('enable_languages', ['0', '1'])->default('0');
            $table->string('language_method', 20)->default('DISABLED');
            $table->string('meetme_enter_login_filename', 255)->nullable();
            $table->string('meetme_enter_leave3way_filename', 255)->nullable();
            $table->enum('enable_did_entry_list_id', ['0', '1'])->default('0');
            $table->enum('enable_third_webform', ['0', '1'])->default('0');
            $table->string('chat_url', 255)->nullable();
            $table->integer('chat_timeout')->unsigned()->nullable();
            $table->string('agent_debug_logging', 20)->default('0');
            $table->string('default_language', 100)->default('default English');
            $table->enum('agent_whisper_enabled', ['0', '1'])->default('0');
            $table->enum('user_hide_realtime_enabled', ['0', '1'])->default('0');
            $table->string('custom_reports_use_slave_db', 2000)->nullable();
            $table->enum('usacan_phone_dialcode_fix', ['0', '1'])->default('0');
            $table->enum('cache_carrier_stats_realtime', ['0', '1'])->default('0');
            $table->datetime('oldest_logs_date')->nullable();
            $table->enum('log_recording_access', ['0', '1'])->default('0');
            $table->enum('report_default_format', ['TEXT', 'HTML'])->default('TEXT');
            $table->enum('alt_ivr_logging', ['0', '1'])->default('0');
            $table->enum('admin_row_click', ['0', '1'])->default('1');
            $table->string('admin_screen_colors', 20)->default('default');
            $table->enum('ofcom_uk_drop_calc', ['1', '0'])->default('0');
            $table->string('agent_screen_colors', 20)->default('default');
            $table->enum('script_remove_js', ['1', '0', '2', '3', '4', '5', '6'])->default('1');
            $table->enum('manual_auto_next', ['1', '0'])->default('0');
            $table->enum('user_new_lead_limit', ['1', '0'])->default('0');
            $table->enum('agent_xfer_park_3way', ['1', '0'])->default('0');
            $table->integer('rec_prompt_count')->unsigned()->default(0);
            $table->enum('agent_soundboards', ['1', '0'])->default('0');
            $table->string('web_loader_phone_length', 10)->default('DISABLED');
            $table->string('agent_script', 50)->default('vicidial.php');
            $table->enum('vdad_debug_logging', ['1', '0'])->default('0');
            $table->string('agent_chat_screen_colors', 20)->default('default');
            $table->enum('enable_auto_reports', ['1', '0'])->default('0');
            $table->enum('enable_pause_code_limits', ['1', '0'])->default('1');
            $table->enum('enable_drop_lists', ['0', '1', '2'])->default('0');
            $table->enum('allow_ip_lists', ['0', '1', '2'])->default('0');
            $table->string('system_ip_blacklist', 30)->nullable();
            $table->enum('recording_auto_start', ['0', '1'])->default('1');
            $table->enum('expired_lists_inactive', ['0', '1'])->default('0');
            $table->enum('did_system_filter', ['0', '1'])->default('0');
            $table->enum('anyone_callback_inactive_lists', ['default', 'NO_ADD_TO_HOPPER', 'KEEP_IN_HOPPER'])->default('default');
            $table->enum('enable_gdpr_download_deletion', ['0', '1', '2'])->default('0');
            $table->enum('source_id_display', ['0', '1'])->default('0');
            $table->string('help_modification_date', 20)->default('0');
            $table->enum('agent_logout_link', ['0', '1', '2', '3', '4'])->default('1');
            $table->enum('manual_dial_validation', ['0', '1', '2', '3', '4'])->default('0');
            $table->enum('mute_recordings', ['1', '0'])->default('0');
            $table->enum('user_admin_redirect', ['1', '0'])->default('0');
            $table->enum('list_status_modification_confirmation', ['1', '0'])->default('0');
            $table->enum('sip_event_logging', ['0', '1', '2', '3', '4', '5', '6', '7'])->default('0');
            $table->enum('call_quota_lead_ranking', ['0', '1', '2'])->default('0');
            $table->enum('enable_second_script', ['0', '1'])->default('0');
            $table->enum('enable_first_webform', ['0', '1'])->default('1');
            $table->string('recording_buttons', 30)->default('START_STOP');
            $table->enum('opensips_cid_name', ['0', '1'])->default('0');
            $table->tinyInteger('require_password_length')->unsigned()->default(0);
            $table->enum('user_account_emails', ['DISABLED', 'SEND_NO_PASS', 'SEND_WITH_PASS'])->default('DISABLED');
            $table->enum('outbound_cid_any', ['DISABLED', 'API_ONLY'])->default('DISABLED');
            $table->tinyInteger('entries_per_page')->unsigned()->default(0);
            $table->enum('browser_call_alerts', ['0', '1', '2'])->default('0');
            $table->enum('queuemetrics_pausereason', ['STANDARD', 'EVERY_NEW', 'EVERY_NEW_ADMINCALL'])->default('STANDARD');
            $table->enum('inbound_answer_config', ['0', '1', '2', '3', '4', '5'])->default('0');
            $table->enum('enable_international_dncs', ['0', '1'])->default('0');
            $table->string('web_loader_phone_strip', 10)->default('DISABLED');
            $table->string('manual_dial_phone_strip', 10)->default('DISABLED');
            $table->enum('daily_call_count_limit', ['0', '1'])->default('0');
            $table->enum('allow_shared_dial', ['0', '1', '2', '3', '4', '5', '6'])->default('0');
            $table->enum('agent_search_method', ['0', '1', '2', '3', '4', '5', '6'])->default('0');
            $table->string('phone_defaults_container', 40)->default('---DISABLED---');
            $table->tinyInteger('qc_claim_limit')->unsigned()->default(3);
            $table->tinyInteger('qc_expire_days')->unsigned()->default(3);
            $table->tinyInteger('two_factor_auth_hours')->default(0);
            $table->string('two_factor_container', 40)->default('---DISABLED---');
            $table->string('agent_hidden_sound', 20)->default('click_quiet');
            $table->tinyInteger('agent_hidden_sound_volume')->unsigned()->default(25);
            $table->tinyInteger('agent_hidden_sound_seconds')->unsigned()->default(0);
            $table->string('agent_screen_timer', 20)->default('setTimeout');
            $table->string('label_lead_id', 60)->nullable();
            $table->string('label_list_id', 60)->nullable();
            $table->string('label_entry_date', 60)->nullable();
            $table->string('label_gmt_offset_now', 60)->nullable();
            $table->string('label_source_id', 60)->nullable();
            $table->string('label_called_since_last_reset', 60)->nullable();
            $table->string('label_status', 60)->nullable();
            $table->string('label_user', 60)->nullable();
            $table->string('label_date_of_birth', 60)->nullable();
            $table->string('label_country_code', 60)->nullable();
            $table->string('label_last_local_call_time', 60)->nullable();
            $table->string('label_called_count', 60)->nullable();
            $table->string('label_rank', 60)->nullable();
            $table->string('label_owner', 60)->nullable();
            $table->string('label_entry_list_id', 60)->nullable();
            $table->enum('call_limit_24hour', ['0', '1'])->default('0');
            $table->datetime('call_limit_24hour_reset')->default('2000-01-01 00:00:01');
            $table->enum('allowed_sip_stacks', ['SIP', 'PJSIP', 'SIP_and_PJSIP'])->default('SIP');
            $table->enum('agent_hide_hangup', ['1', '0', '2', '3', '4', '5', '6'])->default('0');
            $table->enum('allow_web_debug', ['0', '1', '2', '3', '4', '5', '6'])->default('0');
            $table->enum('max_logged_in_agents', ['0', '1', '2', '3', '4', '5', '6', '7'])->default('0');
            $table->enum('user_codes_admin', ['0', '1', '2', '3', '4', '5', '6', '7'])->default('0');
            $table->enum('login_kickall', ['0', '1', '2', '3', '4', '5', '6', '7'])->default('0');
            $table->enum('abandon_check_queue', ['0', '1', '2', '3', '4', '5', '6', '7'])->default('0');
            $table->enum('agent_notifications', ['0', '1', '2', '3', '4', '5', '6', '7'])->default('0');
            $table->enum('demographic_quotas', ['0', '1', '2', '3', '4', '5', '6', '7'])->default('0');
            $table->enum('log_latency_gaps', ['0', '1', '2', '3', '4', '5', '6', '7'])->default('1');
            $table->enum('inbound_credits', ['0', '1', '2', '3', '4', '5', '6', '7'])->default('0');
            $table->enum('weekday_resets', ['0', '1', '2', '3', '4', '5', '6', '7'])->default('0');
            $table->string('hide_inactive_lists', 255)->nullable();
            $table->string('allow_manage_active_lists', 255)->nullable();
            $table->string('agent_push_events', 255)->nullable();
            $table->string('agent_push_url', 255)->nullable();
             $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('system_settings');
    }
}
