<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateVicidialCampaignsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('vicidial_campaigns', function (Blueprint $table) {
            $table->string('campaign_id')->primary();
            $table->string('campaign_name', 40);
            $table->enum('active', ['Y', 'N']);
            $table->string('dial_status_a', 6);
            $table->string('dial_status_b', 6);
            $table->string('dial_status_c', 6);
            $table->string('dial_status_d', 6);
            $table->string('dial_status_e', 6);
            $table->string('lead_order', 30);
            $table->string('park_ext', 10);
            $table->string('park_file_name', 100)->default('default');
            $table->text('web_form_address');
            $table->enum('allow_closers', ['Y', 'N']);
            $table->unsignedInteger('hopper_level')->default(1);
            $table->string('auto_dial_level', 6)->default('0');
            $table->string('next_agent_call', 40)->default('longest_wait_time');
            $table->string('local_call_time', 10)->default('9am-9pm');
            $table->string('voicemail_ext', 10)->nullable();
            $table->unsignedTinyInteger('dial_timeout')->default(60);
            $table->string('dial_prefix', 20)->default('9');
            $table->string('campaign_cid', 20)->default('0000000000');
            $table->string('campaign_vdad_exten', 20)->default('8368');
            $table->string('campaign_rec_exten', 20)->default('8309');
            $table->enum('campaign_recording', ['NEVER', 'ONDEMAND', 'ALLCALLS', 'ALLFORCE'])->default('ONDEMAND');
            $table->string('campaign_rec_filename', 50)->default('FULLDATE_CUSTPHONE');
            $table->string('campaign_script', 20)->nullable();
            $table->enum('get_call_launch', ['NONE', 'SCRIPT', 'SCRIPTTWO', 'WEBFORM', 'WEBFORMTWO'])->default('NONE');
            $table->string('am_message_exten', 100)->default('vm-goodbye');
            $table->enum('amd_send_to_vmx', ['Y', 'N'])->default('N');
            $table->string('xferconf_a_dtmf', 50)->nullable();
            $table->string('xferconf_a_number', 50)->nullable();
            $table->string('xferconf_b_dtmf', 50)->nullable();
            $table->string('xferconf_b_number', 50)->nullable();
            $table->enum('alt_number_dialing', ['N', 'Y', 'SELECTED', 'SELECTED_TIMER_ALT', 'ALL'])->default('N');
            $table->enum('scheduled_callbacks', ['Y', 'N'])->default('N');
            $table->string('lead_filter_id', 20)->default('NONE');
            $table->unsignedTinyInteger('drop_call_seconds')->default(5);
            $table->enum('drop_action', ['HANGUP', 'MESSAGE', 'VOICEMAIL', 'IN_GROUP', 'EXTERNAL'])->default('HANGUP');
            $table->string('safe_harbor_exten', 20)->default('8307');
            $table->enum('display_dialable_count', ['Y', 'N'])->default('Y');
            $table->smallInteger('wrapup_seconds')->unsigned()->default(0);
            $table->string('wrapup_message', 255)->default('Wrapup Call');
            $table->text('closer_campaigns')->nullable();
            $table->enum('use_internal_dnc', ['Y', 'N', 'AREACODE'])->default('N');
            $table->smallInteger('allcalls_delay')->unsigned()->default(0);
            $table->enum('omit_phone_code', ['Y', 'N'])->default('N');
            $table->enum('dial_method', ['MANUAL', 'RATIO', 'ADAPT_HARD_LIMIT', 'ADAPT_TAPERED', 'ADAPT_ABOVE_HARD_LIMIT'])->default('MANUAL');
            $table->enum('available_only_ratio_tally', ['Y', 'N'])->default('N');
            $table->string('adaptive_dropped_percentage', 4)->default('3');
            $table->string('adaptive_maximum_level', 6)->default('3.0');
            $table->string('adaptive_latest_server_time', 4)->default('2100');
            $table->string('adaptive_intensity', 6)->default('0');
            $table->smallInteger('adaptive_dl_diff_target')->unsigned()->default(0);
            $table->enum('concurrent_transfers', ['AUTO', '1', '2', '3', '4', '5', '6', '7', '8', '9'])->default('AUTO');
            $table->enum('auto_alt_dial', ['NONE', 'ALT_ONLY', 'ADDR3_ONLY', 'ALT_AND_ADDR3', 'ALT_AND_ADDR3_BOTH', 'ADDR3_AND_ALT_BOTH'])->default('NONE');
            $table->string('auto_alt_dial_statuses', 255)->default('B N NA DC -');
            $table->enum('agent_pause_codes_active', ['Y', 'N', 'FORCE'])->default('N');
            $table->string('campaign_description', 255)->nullable();
            $table->datetime('campaign_changedate')->nullable();
            $table->enum('campaign_stats_refresh', ['Y', 'N'])->default('N');
            $table->datetime('campaign_logindate')->nullable();
            $table->string('dial_statuses', 255)->default('NEW -');
            $table->enum('disable_alter_custdata', ['Y', 'N'])->default('N');
            $table->enum('no_hopper_leads_logins', ['Y', 'N'])->default('N');
            $table->string('list_order_mix', 20)->default('DISABLED');
            $table->enum('campaign_allow_inbound', ['Y', 'N'])->default('N');
            $table->bigInteger('manual_dial_list_id')->unsigned()->default(998);
            $table->string('default_xfer_group', 20)->default('---NONE---');
            $table->text('xfer_groups')->nullable();
            $table->tinyInteger('queue_priority')->default(50);
            $table->string('drop_inbound_group', 20)->default('---NONE---');
            $table->enum('qc_enabled', ['Y', 'N'])->default('N');
            $table->text('qc_statuses')->nullable();
            $table->text('qc_lists')->nullable();
            $table->string('qc_shift_id', 20)->default('24HRMIDNIGHT');
            $table->enum('qc_get_record_launch', ['NONE', 'SCRIPT', 'WEBFORM', 'QCSCRIPT', 'QCWEBFORM'])->default('NONE');
            $table->enum('qc_show_recording', ['Y', 'N'])->default('Y');
            $table->string('qc_web_form_address', 255)->nullable();
            $table->string('qc_script', 20)->nullable();
            $table->text('survey_first_audio_file')->nullable();
            $table->string('survey_dtmf_digits', 16)->default('1238');
            $table->string('survey_ni_digit', 1)->default('8');
            $table->text('survey_opt_in_audio_file')->nullable();
            $table->text('survey_ni_audio_file')->nullable();
            $table->enum('survey_method', ['AGENT_XFER', 'VOICEMAIL', 'EXTENSION', 'HANGUP', 'NUMBER_INPUT'])->default('AGENT_XFER');
            $table->enum('survey_no_response_action', ['OPTIN', 'OPTOUT', 'DROP'])->default('OPTIN');
            $table->string('survey_ni_status', 6)->default('NI');
            $table->string('survey_response_digit_map', 255)->default('1-DEMOCRAT|2-REPUBLICAN|3-INDEPENDANT|8-OPTOUT|X-NO RESPONSE|');
            $table->string('survey_xfer_exten', 20)->default('8300');
            $table->string('survey_camp_record_dir', 255)->default('/home/survey');
            $table->enum('disable_alter_custphone', ['Y', 'N', 'HIDE'])->default('Y');
            $table->enum('display_queue_count', ['Y', 'N'])->default('Y');
            $table->string('manual_dial_filter', 50)->default('NONE');
            $table->string('agent_clipboard_copy', 50)->default('NONE');
            $table->enum('agent_extended_alt_dial', ['Y', 'N'])->default('N');
            $table->enum('use_campaign_dnc', ['Y', 'N', 'AREACODE'])->default('N');
            $table->enum('three_way_call_cid', ['CAMPAIGN', 'CUSTOMER', 'AGENT_PHONE', 'AGENT_SELECTED'])->default('CAMPAIGN');
            $table->string('three_way_dial_prefix', 20)->nullable();
            $table->string('web_form_target', 100)->default('vdcwebform');
            $table->string('vtiger_search_category', 100)->default('LEAD');
            $table->enum('vtiger_create_call_record', ['Y', 'N', 'DISPO'])->default('Y');
            $table->enum('vtiger_create_lead_record', ['Y', 'N'])->default('Y');
            $table->enum('vtiger_screen_login', ['Y', 'N', 'NEW_WINDOW'])->default('Y');
            $table->enum('cpd_amd_action', ['DISABLED', 'DISPO', 'MESSAGE', 'CALLMENU', 'SCRIPT', 'WEBFORM'])->default('DISABLED');
            $table->enum('agent_allow_group_alias', ['Y', 'N'])->default('N');
            $table->string('default_group_alias', 30)->nullable();
            $table->enum('vtiger_search_dead', ['DISABLED', 'ASK', 'RESURRECT'])->default('ASK');
            $table->enum('vtiger_status_call', ['Y', 'N'])->default('N');
            $table->string('survey_third_digit', 1)->nullable();
            $table->text('survey_third_audio_file')->nullable();
            $table->string('survey_third_status', 6)->default('NI');
            $table->string('survey_third_exten', 20)->default('8300');
            $table->string('survey_fourth_digit', 1)->nullable();
            $table->text('survey_fourth_audio_file')->nullable();
            $table->string('survey_fourth_status', 6)->default('NI');
            $table->string('survey_fourth_exten', 20)->default('8300');
            $table->string('drop_lockout_time', 6)->default('0');
            $table->string('quick_transfer_button', 20)->default('N');
            $table->enum('prepopulate_transfer_preset', ['N', 'PRESET_1', 'PRESET_2', 'PRESET_3', 'PRESET_4'])->default('N');
            $table->string('drop_rate_group', 20)->default('DISABLED');
            $table->enum('view_calls_in_queue', ['NONE', 'ALL', '1', '2', '3', '4', '5'])->default('NONE');
            $table->enum('view_calls_in_queue_launch', ['AUTO', 'MANUAL'])->default('MANUAL');
            $table->enum('grab_calls_in_queue', ['Y', 'N'])->default('N');
            $table->enum('call_requeue_button', ['Y', 'N'])->default('N');
            $table->enum('pause_after_each_call', ['Y', 'N'])->default('N');
            $table->enum('no_hopper_dialing', ['Y', 'N'])->default('N');
            $table->enum('agent_dial_owner_only', ['NONE', 'USER', 'TERRITORY', 'USER_GROUP', 'USER_CAMP', 'TERRITORY_CAMP'])->default('NONE');
            $table->enum('agent_display_dialable_leads', ['Y', 'N'])->default('N');
            $table->text('web_form_address_two')->nullable();
            $table->string('waitforsilence_options', 25)->nullable();
            $table->enum('agent_select_territories', ['Y', 'N'])->default('N');
            $table->datetime('campaign_calldate')->nullable();
            $table->enum('crm_popup_login', ['Y', 'N'])->default('N');
            $table->text('crm_login_address')->nullable();
            $table->string('timer_action', 20)->default('NONE');
            $table->string('timer_action_message', 255)->nullable();
            $table->mediumInteger('timer_action_seconds')->default(-1);
            $table->text('start_call_url')->nullable();
            $table->text('dispo_call_url')->nullable();
            $table->string('xferconf_c_number', 50)->nullable();
            $table->string('xferconf_d_number', 50)->nullable();
            $table->string('xferconf_e_number', 50)->nullable();
            $table->enum('use_custom_cid', ['Y', 'N', 'AREACODE', 'USER_CUSTOM_1', 'USER_CUSTOM_2'])->default('N');
            $table->enum('scheduled_callbacks_alert', ['NONE', 'BLINK', 'RED', 'BLINK_RED', 'BLINK_DARK_RED'])->default('NONE');
            $table->enum('queuemetrics_callstatus_override', ['DISABLED', 'NO', 'YES'])->default('DISABLED');
            $table->enum('extension_appended_cidname', ['Y', 'N', 'Y_USER', 'Y_WITH_CAMPAIGN', 'Y_USER_CAMPAIGN'])->default('N');
            $table->enum('scheduled_callbacks_count', ['LIVE', 'ALL_ACTIVE'])->default('ALL_ACTIVE');
            $table->enum('manual_dial_override', ['NONE', 'ALLOW_ALL', 'DISABLE_ALL'])->default('NONE');
            $table->enum('blind_monitor_warning', ['DISABLED', 'ALERT', 'NOTICE', 'AUDIO', 'ALERT_AUDIO'])->default('DISABLED');
            $table->string('blind_monitor_message', 255)->default('Someone is blind monitoring your session');
            $table->string('blind_monitor_filename', 100)->nullable();
            $table->enum('inbound_queue_no_dial', ['DISABLED', 'ENABLED', 'ALL_SERVERS', 'ENABLED_ALL_SERVERS'])->default('DISABLED');
            $table->string('timer_action_destination', 30)->nullable();
            $table->enum('enable_xfer_presets', ['DISABLED', 'ENABLED', 'STAGING', 'CONTACTS'])->default('DISABLED');
            $table->enum('hide_xfer_number_to_dial', ['DISABLED', 'ENABLED'])->default('DISABLED');
            $table->string('manual_dial_prefix', 20)->nullable();
            $table->enum('customer_3way_hangup_logging', ['DISABLED', 'ENABLED'])->default('ENABLED');
            $table->smallInteger('customer_3way_hangup_seconds')->default(5);
            $table->enum('customer_3way_hangup_action', ['NONE', 'DISPO'])->default('NONE');
            $table->enum('ivr_park_call', ['DISABLED', 'ENABLED', 'ENABLED_PARK_ONLY', 'ENABLED_ROUTE_ONLY'])->default('DISABLED');
            $table->text('ivr_park_call_agi')->nullable();
            $table->enum('manual_preview_dial', ['DISABLED', 'PREVIEW_AND_SKIP', 'PREVIEW_ONLY'])->default('PREVIEW_AND_SKIP');
            $table->enum('realtime_agent_time_stats', ['DISABLED', 'WAIT_CUST_ACW', 'WAIT_CUST_ACW_PAUSE', 'CALLS_WAIT_CUST_ACW_PAUSE'])->default('CALLS_WAIT_CUST_ACW_PAUSE');
            $table->enum('use_auto_hopper', ['Y', 'N'])->default('Y');
            $table->string('auto_hopper_multi', 6)->default('1');
            $table->mediumInteger('auto_hopper_level')->unsigned()->default(0);
            $table->enum('auto_trim_hopper', ['Y', 'N'])->default('Y');
            $table->enum('api_manual_dial', ['STANDARD', 'QUEUE', 'QUEUE_AND_AUTOCALL'])->default('STANDARD');
            $table->enum('manual_dial_call_time_check', ['DISABLED', 'ENABLED'])->default('DISABLED');
            $table->enum('display_leads_count', ['Y', 'N'])->default('N');
            $table->enum('lead_order_randomize', ['Y', 'N'])->default('N');
            $table->enum('lead_order_secondary', ['LEAD_ASCEND', 'LEAD_DESCEND', 'CALLTIME_ASCEND', 'CALLTIME_DESCEND'])->default('LEAD_ASCEND');
            $table->enum('per_call_notes', ['ENABLED', 'DISABLED'])->default('DISABLED');
            $table->enum('my_callback_option', ['CHECKED', 'UNCHECKED'])->default('UNCHECKED');
            $table->enum('agent_lead_search', ['ENABLED', 'LIVE_CALL_INBOUND', 'LIVE_CALL_INTERNAL'])->default('ENABLED');
            $table->string('agent_lead_search_method', 30)->default('CAMPLISTS_ALL');
            $table->string('queuemetrics_phone_environment', 20)->nullable();
            $table->enum('auto_pause_precall', ['Y', 'N'])->default('N');
            $table->string('auto_pause_precall_code', 6)->default('PRECAL');
            $table->enum('auto_resume_precall', ['Y', 'N'])->default('N');
            $table->enum('manual_dial_cid', ['CAMPAIGN', 'AGENT_PHONE', 'AGENT_PHONE_OVERRIDE', 'AGENT_PHONE_OVERRIDEBOTH', 'AGENT_CUSTOM_CID'])->default('CAMPAIGN');
            $table->string('post_phone_time_diff_alert', 30)->default('DISABLED');
            $table->string('custom_3way_button_transfer', 30)->default('DISABLED');
            $table->enum('available_only_tally_threshold', ['DISABLED', 'LOGGED-IN_AGENTS', 'NON-PAUSED_AGENTS'])->default('DISABLED');
            $table->smallInteger('available_only_tally_threshold_agents')->unsigned()->default(0);
            $table->enum('dial_level_threshold', ['DISABLED', 'LOGGED-IN_AGENTS', 'NON-PAUSED_AGENTS'])->default('DISABLED');
            $table->smallInteger('dial_level_threshold_agents')->unsigned()->default(0);
            $table->string('safe_harbor_audio', 100)->default('buzz');
            $table->string('safe_harbor_menu_id', 50)->nullable();
            $table->string('survey_menu_id', 50)->nullable();
            $table->smallInteger('callback_days_limit')->unsigned()->default(0);
            $table->enum('dl_diff_target_method', ['ADAPT_CALC_ONLY', 'CALLS_PLACED'])->default('ADAPT_CALC_ONLY');
            $table->enum('disable_dispo_screen', ['DISPO_ENABLED', 'DISPO_DISABLED', 'DISPO_SELECTABLE'])->default('DISPO_ENABLED');
            $table->string('disable_dispo_status', 6)->nullable();
            $table->string('screen_labels', 20)->default('--SYSTEM-SETTINGS--');
            $table->string('status_display_fields', 30)->default('CALLID');
            $table->text('na_call_url')->nullable();
            $table->enum('survey_recording', ['Y', 'N', 'Y_WITH_AMD'])->default('N');
            $table->enum('pllb_grouping', ['DISABLED', 'ONE_SERVER_ONLY', 'CASCADING'])->default('DISABLED');
            $table->smallInteger('pllb_grouping_limit')->unsigned()->default(50);
            $table->smallInteger('call_count_limit')->unsigned()->default(0);
            $table->smallInteger('call_count_target')->unsigned()->default(3);
            $table->tinyInteger('callback_hours_block')->unsigned()->default(0);
            $table->enum('callback_list_calltime', ['ENABLED', 'DISABLED'])->default('DISABLED');
            $table->string('user_group', 20)->default('---ALL---');
            $table->enum('hopper_vlc_dup_check', ['Y', 'N'])->default('N');
            $table->enum('in_group_dial', ['DISABLED', 'MANUAL_DIAL', 'NO_DIAL', 'BOTH'])->default('DISABLED');
            $table->enum('in_group_dial_select', ['AGENT_SELECTED', 'CAMPAIGN_SELECTED', 'ALL_USERS'])->default('CAMPAIGN_SELECTED');
            $table->string('safe_harbor_audio_field', 30)->default('DISABLED');
            $table->enum('pause_after_next_call', ['ENABLED', 'DISABLED'])->default('DISABLED');
            $table->enum('owner_populate', ['ENABLED', 'DISABLED'])->default('DISABLED');
            $table->string('use_other_campaign_dnc', 8)->nullable();
            $table->enum('allow_emails', ['Y', 'N'])->default('N');
            $table->string('amd_inbound_group', 20)->nullable();
            $table->string('amd_callmenu', 50)->nullable();
            $table->tinyInteger('survey_wait_sec')->unsigned()->default(10);
            $table->enum('manual_dial_lead_id', ['Y', 'N'])->default('N');
            $table->smallInteger('dead_max')->unsigned()->default(0);
            $table->string('dead_max_dispo', 6)->default('DCMX');
            $table->smallInteger('dispo_max')->unsigned()->default(0);
            $table->string('dispo_max_dispo', 6)->default('DISMX');
            $table->smallInteger('pause_max')->unsigned()->default(0);
            $table->smallInteger('max_inbound_calls')->unsigned()->default(0);
            $table->enum('manual_dial_search_checkbox', ['SELECTED', 'SELECTED_RESET', 'UNSELECTED', 'SELECTED_MULTI'])->default('SELECTED');
            $table->enum('hide_call_log_info', ['Y', 'N', 'SHOW_1', 'SHOW_2', 'SHOW_3', 'SHOW_ALL'])->default('N');
            $table->smallInteger('timer_alt_seconds')->unsigned()->default(0);
            $table->enum('wrapup_bypass', ['DISABLED', 'ENABLED'])->default('ENABLED');
            $table->enum('wrapup_after_hotkey', ['DISABLED', 'ENABLED'])->default('DISABLED');
            $table->smallInteger('callback_active_limit')->unsigned()->default(0);
            $table->enum('callback_active_limit_override', ['N', 'Y'])->default('N');
            $table->enum('allow_chats', ['Y', 'N'])->default('N');
            $table->enum('comments_all_tabs', ['DISABLED', 'ENABLED'])->default('DISABLED');
            $table->enum('comments_dispo_screen', ['DISABLED', 'ENABLED', 'REPLACE_CALL_NOTES'])->default('DISABLED');
            $table->enum('comments_callback_screen', ['DISABLED', 'ENABLED', 'REPLACE_CB_NOTES'])->default('DISABLED');
            $table->enum('qc_comment_history', ['CLICK', 'AUTO_OPEN', 'CLICK_ALLOW_MINIMIZE', 'AUTO_OPEN_MINIMIZE'])->default('CLICK');
            $table->enum('show_previous_callback', ['DISABLED', 'ENABLED'])->default('ENABLED');
            $table->enum('clear_script', ['DISABLED', 'ENABLED'])->default('DISABLED');
            $table->enum('cpd_unknown_action', ['DISABLED', 'DISPO', 'MESSAGE', 'CALLMENU', 'AMDACT', 'PARKCALL'])->default('DISABLED');
            $table->string('manual_dial_search_filter', 50)->default('NONE');
            $table->text('web_form_address_three')->nullable();
            $table->enum('manual_dial_override_field', ['ENABLED', 'DISABLED'])->default('ENABLED');
            $table->enum('status_display_ingroup', ['ENABLED', 'DISABLED'])->default('ENABLED');
            $table->smallInteger('customer_gone_seconds')->unsigned()->default(30);
            $table->string('agent_display_fields', 100)->nullable();
            $table->enum('am_message_wildcards', ['Y', 'N'])->default('N');
            $table->string('manual_dial_timeout', 3)->nullable();
            $table->enum('routing_initiated_recordings', ['Y', 'N'])->default('N');
            $table->enum('manual_dial_hopper_check', ['Y', 'N'])->default('N');
            $table->mediumInteger('callback_useronly_move_minutes')->unsigned()->default(0);
            $table->enum('ofcom_uk_drop_calc', ['Y', 'N'])->default('N');
            $table->smallInteger('manual_auto_next')->unsigned()->default(0);
            $table->enum('manual_auto_show', ['Y', 'N'])->default('N');
            $table->enum('allow_required_fields', ['Y', 'N'])->default('N');
            $table->enum('dead_to_dispo', ['ENABLED', 'DISABLED'])->default('DISABLED');
            $table->enum('agent_xfer_validation', ['N', 'Y'])->default('N');
            $table->mediumInteger('ready_max_logout')->unsigned()->default(0);
            $table->smallInteger('callback_display_days')->unsigned()->default(0);
            $table->enum('three_way_record_stop', ['Y', 'N'])->default('N');
            $table->enum('hangup_xfer_record_start', ['Y', 'N'])->default('N');
            $table->enum('external_iframe_enabled', ['Y', 'N'])->default('N');
            $table->string('disposition_type', 50)->nullable();
            $table->string('max_pause_sec', 250)->nullable();
            $table->enum('scheduled_callbacks_email_alert', ['Y', 'N'])->default('N');
            $table->enum('max_inbound_calls_outcome', ['DEFAULT', 'ALLOW_AGENTDIRECT', 'ALLOW_MI_PAUSE'])->default('DEFAULT');
            $table->enum('manual_auto_next_options', ['DEFAULT', 'PAUSE_NO_COUNT'])->default('DEFAULT');
            $table->string('agent_screen_time_display', 40)->default('DISABLED');
            $table->enum('next_dial_my_callbacks', ['DISABLED', 'ENABLED'])->default('DISABLED');
            $table->string('inbound_no_agents_no_dial_container', 40)->default('---DISABLED---');
            $table->smallInteger('inbound_no_agents_no_dial_threshold')->unsigned()->default(0);
            $table->string('cid_group_id', 20)->default('---DISABLED---');
            $table->string('pause_max_dispo', 6)->default('PAUSMX');
            $table->enum('script_top_dispo', ['Y', 'N'])->default('N');
            $table->smallInteger('dead_trigger_seconds')->unsigned()->default(0);
            $table->enum('dead_trigger_action', ['DISABLED', 'AUDIO', 'URL', 'AUDIO_AND_URL'])->default('DISABLED');
            $table->enum('dead_trigger_repeat', ['NO', 'REPEAT_ALL', 'REPEAT_AUDIO', 'REPEAT_URL'])->default('NO');
            $table->text('dead_trigger_filename')->nullable();
            $table->text('dead_trigger_url')->nullable();
            $table->enum('scheduled_callbacks_force_dial', ['N', 'Y'])->default('N');
            $table->string('scheduled_callbacks_auto_reschedule', 10)->default('DISABLED');
            $table->string('scheduled_callbacks_timezones_container', 40)->default('DISABLED');
            $table->string('three_way_volume_buttons', 20)->default('ENABLED');
            $table->enum('callback_dnc', ['ENABLED', 'DISABLED'])->default('DISABLED');
            $table->enum('manual_dial_validation', ['Y', 'N'])->default('N');
            $table->enum('mute_recordings', ['Y', 'N'])->default('N');
            $table->string('auto_active_list_new', 20)->default('DISABLED');
            $table->string('call_quota_lead_ranking', 40)->default('DISABLED');
            $table->tinyInteger('call_quota_process_running')->unsigned()->default(0);
            $table->datetime('call_quota_last_run_date')->nullable();
            $table->string('sip_event_logging', 40)->default('DISABLED');
            $table->string('campaign_script_two', 20)->nullable();
            $table->enum('leave_vm_no_dispo', ['ENABLED', 'DISABLED'])->default('DISABLED');
            $table->string('leave_vm_message_group_id', 40)->default('---NONE---');
            $table->string('dial_timeout_lead_container', 40)->default('DISABLED');
            $table->enum('amd_type', ['AMD', 'CPD', 'KHOMP'])->default('AMD');
            $table->tinyInteger('vmm_daily_limit')->unsigned()->default(0);
            $table->string('opensips_cid_name', 15)->nullable();
            $table->enum('amd_agent_route_options', ['ENABLED', 'DISABLED', 'PENDING'])->default('DISABLED');
            $table->string('browser_alert_sound', 20)->default('---NONE---');
            $table->tinyInteger('browser_alert_volume')->unsigned()->default(50);
            $table->string('three_way_record_stop_exception', 40)->default('DISABLED');
            $table->string('pause_max_exceptions', 40)->nullable();
            $table->string('hopper_drop_run_trigger', 1)->default('N');
            $table->tinyInteger('daily_call_count_limit')->unsigned()->default(0);
            $table->string('daily_limit_manual', 20)->default('DISABLED');
            $table->string('transfer_button_launch', 12)->default('NONE');
            $table->tinyInteger('shared_dial_rank')->unsigned()->default(99);
            $table->string('agent_search_method', 2)->nullable();
            $table->string('qc_scorecard_id', 20)->nullable();
            $table->string('qc_statuses_id', 20)->nullable();
            $table->enum('clear_form', ['DISABLED', 'ENABLED', 'ACKNOWLEDGE'])->default('ACKNOWLEDGE');
            $table->enum('leave_3way_start_recording', ['DISABLED', 'ALL_CALLS', 'ALL_BUT_EXCEPTIONS'])->default('DISABLED');
            $table->string('leave_3way_start_recording_exception', 40)->default('DISABLED');
            $table->string('calls_waiting_vl_one', 25)->default('DISABLED');
            $table->string('calls_waiting_vl_two', 25)->default('DISABLED');
            $table->string('calls_inqueue_count_one', 40)->default('DISABLED');
            $table->string('calls_inqueue_count_two', 40)->default('DISABLED');
            $table->smallInteger('in_man_dial_next_ready_seconds')->unsigned()->default(0);
            $table->string('in_man_dial_next_ready_seconds_override', 40)->default('DISABLED');
            $table->enum('transfer_no_dispo', ['DISABLED', 'EXTERNAL_ONLY', 'LOCAL_ONLY', 'LEAD_ONLY', 'ALWAYS'])->default('DISABLED');
            $table->enum('call_limit_24hour_method', ['DISABLED', 'PHONE_NUMBER', 'LEAD'])->default('DISABLED');
            $table->enum('call_limit_24hour_scope', ['SYSTEM_WIDE', 'CAMPAIGN_LISTS'])->default('SYSTEM_WIDE');
            $table->tinyInteger('call_limit_24hour')->unsigned()->default(0);
            $table->string('call_limit_24hour_override', 40)->default('DISABLED');
            $table->string('cid_group_id_two', 20)->default('---DISABLED---');
            $table->smallInteger('incall_tally_threshold_seconds')->unsigned()->default(0);
            $table->tinyInteger('auto_alt_threshold')->unsigned()->default(0);
            $table->text('pause_max_url')->nullable();
            $table->enum('agent_hide_hangup', ['Y', 'N'])->default('N');
            $table->enum('ig_xfer_list_sort', ['GROUP_ID_UP', 'GROUP_ID_DOWN', 'GROUP_NAME_UP', 'GROUP_NAME_DOWN'])->default('GROUP_ID_UP');
            $table->string('script_tab_frame_size', 10)->default('DEFAULT');
            $table->smallInteger('max_logged_in_agents')->unsigned()->default(0);
            $table->enum('user_group_script', ['DISABLED', 'ENABLED'])->default('DISABLED');
            $table->enum('agent_hangup_route', ['HANGUP', 'MESSAGE', 'EXTENSION', 'IN_GROUP', 'CALLMENU'])->default('HANGUP');
            $table->text('agent_hangup_value')->nullable();
            $table->enum('agent_hangup_ig_override', ['Y', 'N'])->default('N');
            $table->enum('show_confetti', ['DISABLED', 'SALES', 'CALLBACKS', 'SALES_AND_CALLBACKS'])->default('DISABLED');
            $table->enum('demographic_quotas', ['DISABLED', 'ENABLED', 'INVALID', 'COMPLETE'])->default('DISABLED');
            $table->string('demographic_quotas_container', 40)->default('DISABLED');
            $table->enum('demographic_quotas_rerank', ['NO', 'NOW', 'HOUR', 'MINUTE', 'NOW_HOUR'])->default('NO');
            $table->datetime('demographic_quotas_last_rerank')->default('2000-01-01 00:00:00');
            $table->enum('demographic_quotas_list_resets', ['AUTO', 'MANUAL'])->default('MANUAL');
            $table->text('custom_one')->nullable();
            $table->text('custom_two')->nullable();
            $table->text('custom_three')->nullable();
            $table->text('custom_four')->nullable();
            $table->text('custom_five')->nullable();
            $table->enum('dead_stop_recording', ['DISABLED', 'ALL_CALLS', 'OUTBOUND_ONLY', 'INBOUND_ONLY'])->default('DISABLED');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('vicidial_campaigns');
    }
}
